# Generated by Django 5.2.1 on 2025-05-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="especialidad",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
